name: Regenerate component definition content
on:
  push:
    branches:
      - main
    paths:
      - 'profiles/**'
      - 'markdown/profiles/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Regenerate content
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Trestle
        run: make trestle-install
      - name: Regenerate component-definitions
        run: make regenerate-cd
      - name: Update and PR
        run: bash ./automation/lib/update.sh "Sync OSCAL component definitions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}